### PR TITLE
FIX: Set python_min of Python 3.8

### LINKED ISSUE #47: Incorrect minimum Python version
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This conda-forge package specifies `python >=3.7` as a dependency.  Although it is not exactly clear from the hatch Github repo whether this is also indicated there for hatchling or when it might have been for hatchling, the current version of hatchling.dep.core definitely raises an exception in Python 3.7:

```
  File "C:\...\lib\site-packages\hatchling\dep\core.py", line 5, in <module>
    from importlib.metadata import Distribution, DistributionFinder
ModuleNotFoundError: No module named 'importlib.metadata'
```

### Installed packages

```shell
N/A
```

### Environment info

```shell
N/A
```

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Resolves https://github.com/conda-forge/hatchling-feedstock/issues/47
* Required to fix https://github.com/conda-forge/pyhf-feedstock/pull/28#issuecomment-2464060369

## Description

* Use `python {{ python_min }}` syntax for the python requirements for noarch python recipes.
   - c.f. https://conda-forge.org/docs/maintainer/knowledge_base/#noarch-python
* Add `recipe/conda_build_config.yaml` to override the global `python_min` with `hatchling`'s `python_min` of `3.8`.
* Install with recommended `--no-deps --no-build-isolation` options to ensure build dependencies are correct.
* Update to `pypi.org`.
* Bump build number.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [N/A] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
> * No valid build backend found for Python recipe for package `hatchling` using `pip`. Python recipes using `pip` need to explicitly specify a build backend in the `host` section. If your recipe has built with only `pip` in the `host` section in the past, you likely should add `setuptools` to the `host` section of your recipe.

I assume that build backends are immune from this. I'm not sure if there is some way to indicate to conda-forge that they are self sufficient.

**Comment by matthewfeickert** [comment]
@conda-forge/hatchling this is ready for review.

**Review by ofek — APPROVED** [review]
Good catch, thank you!

**Comment by matthewfeickert** [comment]
Thanks @ofek. Can I also get you to :+1: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/901 ?

**Pull request merged**
